### ISSUE TITLE
aliri_oauth2::Authority::new_from_url errors if an unknown algorithm is encountered

### ISSUE THREAD

**Issue by netthier** [neoeinstein/aliri#11]
Even if multiple algorithms are offered, the deserialization of the response will fail if any unsupported algorithm is offered.
My Keycloak server provides both RS256 and RSA-OAEP algorithms.
Running
```rust
let authority =
        aliri_oauth2::Authority::new_from_url("https://example.com/auth/realms/master/protocol/openid-connect/certs", oauth_validator)
            .await?;
```
fails with
```
Error: error decoding response body: data did not match any variant of untagged enum Algorithm at line 1 column 90
```
with column 90 containing `"alg": "RSA-OAEP"`

**Comment by netthier** [comment]
Disabling RSA-OAEP in Keycloak fixes this issue, but I think there should be a way to handle unknown algorithms in aliri.

**Comment by neoeinstein** [comment]
That certainly sounds reasonable. I may be able to add something in to identify that it is an unsupported key type and log a warning, but continue operating normally.
