### ISSUE TITLE
Decomposed and custom Header structs

### ISSUE THREAD

**Issue by smndtrl** [neoeinstein/aliri#24]
Hi,

i couldn't find how to use custom Headers and decompose together. Using the naive approach

```
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct AbcHeaders {
    pub alg: Algorithm,
    pub jwk: Jwk,
    pub nonce: String,
    pub url: String
}

let decomp = token.decompose::<AbcHeaders>().unwrap();
```
didn't allow me to access the content of the AbcHeaders. Also implementing a trait for Decomposed does not work as self.header is inaccessible as its pub(crate).

Am i missing something obvious?

**Comment by neoeinstein** [comment]
Indeed, it looks like `Decomposed` itself is not providing access to the headers or payload until it passes through `verify()`. If you need these for your use case, we could add some accessors that make it clear the header or payload you might be reading is _not_ verified. Something like `decop.untrusted_header()` and `decomp.untrusted_payload()`. Would that help to satisfy your use case?

**Comment by smndtrl** [comment]
I would be happy with the `untrusted_header()` function. I need it for the new account API in the ACME protocol [spec](https://www.rfc-editor.org/rfc/rfc8555.html#section-7.3) where I'll get the public key along with the signature. So I need to have a way of getting the header info because your API requires the parameters for verify.

The only other way i could imagine is a `try_verify_internal()` that uses the header info and the included JWK internally. Obviously won't work with `kid` tokens and is more work. I might revisit something similar for my abstraction in order to provide my downstream consumers with a easy way of handling the signup scenario.

In the end your first proposal is perfectly fine for my scenario as I know how to handle the rest.
