### ISSUE TITLE
aliri_axum: support axum 0.7

### ISSUE THREAD

**Issue by martyn-v** [neoeinstein/aliri#44]
Axum has had a number of api changes in [0.7](https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md#070-27-november-2023) which make this crate incompatible.

**Comment by neoeinstein** [comment]
This is largely complete (pending release). I've opted to defer updating `aliri_reqwest` until after `reqwest-middleware` releases their update to use `reqwest 0.12`, at which point all the main crates (except `actix` and `warp`) will be on the `http 1.0` line.
